<!ENTITY color_NN "white"><!-- differs from bbbike, distinction just by width -->
<!ENTITY color_N  "white"><!-- not using grey98 here -->
<!ENTITY color_NH "#ffffb0">
<!ENTITY color_H  "#ffff90">
<!ENTITY color_HH "#fff800">

<!ENTITY color_Q0 "#698B69">
<!ENTITY color_Q1 "#9ACD32">
<!ENTITY color_Q2 "#FFD700">
<!ENTITY color_Q3 "#f00">

<!ENTITY color_RW2 "#00008b">
<!ENTITY color_RW4 "#70c986">
<!ENTITY color_RW5 "orange">
